### ISSUE TITLE
⚠️

### ISSUE THREAD

**Issue by dohooo** [jamninetyfive/dangautoanswer#1]
Hey 你开源了很多人的身份证号码诶。

**Comment by jamninetyfive** [comment]
对哦，感谢提醒，几年了没注意。

看到你写的https://github.com/dohooo/react-native-reanimated-carousel 库真的很赞。
正在研究，项目上有需求要写一个下拉二楼悬停的效果，看看能不能借鉴到一些思路。

**Comment by dohooo** [comment]
可以在 [discord](https://discord.gg/SZrTk2UX) 上可以找到我，有问题可以一起讨论。 
不过你的需求之前貌似有人提过，但我没想明白这样子的需求怎么会联想到轮播图组件 ，hh

**Comment by jamninetyfive** [comment]
react native + reanimated 关键词搜出来的，先star再说，关系很大，基本没写过动画，这对于我想知道如何实现动画这个过程太重要了。哈哈
